server:
  port: 8160

wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ulogin/wx/callback

spring:
  application:
    name: spring-cloud-nacos-wxLogin-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/keepstudy?useUnicode=true&characterEncoding=utf-8
    username: keepstudy
    password: 123456
  profiles:
    active: dev

#management:
#  endpoint:
#    web:
#      exposure:
#        include: *
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
